--- !Config
bwuser: 'email address'
bwpass: 'password'
guardianid: null
childids: []
bwurl: 'https://schools.mybrightwheel.com'
startdate: '01/01/2018'
enddate: '07/07/2019'
startpage: 0
pagesize: 10
timezone: 'America/Denver'
